name: "Publish Next Function"
description: "Publish Serverless NextJS using Azure Functions and Storage"
inputs:
  configuration:
    description: "Configuration for resources, build and deployment."
    required: true
  app-settings:
    description: "JSON object containing key: values of any app settings to configure on the function app."
    required: false
  pull-request:
    description: "If true, this will deploy a unique instance based on the pull request information."
    required: false
    default: false
  github-token:
    description: "Github token to access github resources required during the workflow. For example posting a comment in the PR. Required if 'pull-request' is true."
    required: false
runs:
  using: "node12"
  main: "src/index.js"